services:
  - type: web
    name: beauvia
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: WHATSAPP_NUMBER
        value: 7736317618
